import fs from "node:fs/promises";
import path from "node:path";
import Link from "next/link";

/* eslint-disable @next/next/no-img-element */

/**
 * Showcase gallery: films made end-to-end by the Nemotron crew, each with
 * its full trace (every model call, score, token count and cost). Public
 * even in demo mode. Data: public/showcase/index.json, written by
 * `npm run director:showcase` from REAL runs only.
 */

export const dynamic = "force-dynamic";

interface ShowcaseFilm {
  slug: string;
  title: string;
  language: string;
  logline: string;
  story: string;
  film: string;
  poster: string;
  trace: string;
  models: Record<string, string>;
  provider: string;
  summary: {
    shots: number;
    rendered: number;
    firstPassOk: number;
    repairs: number;
    criticBefore: number | null;
    criticAfter: number | null;
    revisions: number;
    lintErrors: number;
    lintWarnings: number;
    durationSec: number;
    wallMs: number;
    tokens: number;
    costUsd: number;
    textCritic: boolean;
  };
  createdAt: string;
}

async function loadFilms(): Promise<ShowcaseFilm[]> {
  try {
    const raw = await fs.readFile(path.join(process.cwd(), "public", "showcase", "index.json"), "utf8");
    return (JSON.parse(raw) as { films: ShowcaseFilm[] }).films;
  } catch {
    return [];
  }
}

const LANG: Record<string, string> = { en: "English", vi: "Tiếng Việt", ja: "日本語" };

export default async function ShowcasePage() {
  const films = await loadFilms();
  return (
    <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-10">
      <header className="mb-8 flex flex-wrap items-center gap-3">
        <div className="btn-gradient h-10 w-10 rounded-xl" />
        <div className="flex-1">
          <h1 className="text-2xl font-bold">Showcase · Phim mẫu</h1>
          <p className="text-sm text-muted">
            Films made end to end by the NVIDIA Nemotron crew on Nebius Token Factory: Ultra plans, Super draws every frame as code, Nano Omni critiques the renders, Nano edits. Every
            film links its full trace. / Phim do đội Nemotron làm từ đầu đến cuối, kèm toàn bộ nhật ký.
          </p>
        </div>
        <Link href="/" className="rounded-xl border border-line px-4 py-2 text-sm text-muted hover:border-accent hover:text-ink">
          ← Studio
        </Link>
      </header>
      {films.length === 0 ? (
        <p className="rounded-card border border-line bg-card p-6 text-muted">
          No showcase films yet. They are generated by real Nemotron runs (<code>npm run director:showcase</code>), never by the mock crew.
        </p>
      ) : (
        <div className="grid gap-6 md:grid-cols-2">
          {films.map((f) => (
            <article key={f.slug} className="overflow-hidden rounded-card border border-line bg-card">
              <video src={f.film} poster={f.poster} controls preload="none" className="aspect-video w-full bg-black" />
              <div className="p-5">
                <div className="flex items-center gap-2 text-xs text-muted">
                  <span className="rounded-full border border-line px-2 py-0.5">{LANG[f.language] ?? f.language}</span>
                  <span>{new Date(f.createdAt).toISOString().slice(0, 10)}</span>
                  <span>· {f.provider}</span>
                </div>
                <h2 className="mt-2 text-lg font-bold">{f.title}</h2>
                <p className="mt-1 text-sm text-muted">{f.logline}</p>
                <dl className="mt-4 grid grid-cols-3 gap-2 text-center text-xs">
                  <Stat k="shots" v={`${f.summary.rendered}/${f.summary.shots}`} />
                  <Stat k="first-pass" v={`${f.summary.firstPassOk}/${f.summary.shots}`} />
                  <Stat k="repairs" v={String(f.summary.repairs)} />
                  <Stat k={f.summary.textCritic ? "critic (text)" : "critic"} v={f.summary.criticBefore !== null ? `${f.summary.criticBefore} → ${f.summary.criticAfter}` : "—"} />
                  <Stat k="tokens" v={f.summary.tokens.toLocaleString("en")} />
                  <Stat k="cost" v={`$${f.summary.costUsd.toFixed(3)}`} />
                </dl>
                <details className="mt-4 text-xs text-muted">
                  <summary className="cursor-pointer">Story · crew · trace</summary>
                  <p className="mt-2 whitespace-pre-wrap text-ink/80">{f.story}</p>
                  <ul className="mt-2 space-y-0.5">
                    {Object.entries(f.models).map(([k, m]) => (
                      <li key={k}>
                        <b>{k}</b>: {m || "text critic"}
                      </li>
                    ))}
                  </ul>
                  <a href={f.trace} className="mt-2 inline-block text-accent underline">
                    trace.json
                  </a>{" "}
                  · {Math.round(f.summary.durationSec)} s film · {Math.round(f.summary.wallMs / 1000)} s to make
                </details>
              </div>
            </article>
          ))}
        </div>
      )}
    </main>
  );
}

function Stat({ k, v }: { k: string; v: string }) {
  return (
    <div className="rounded-lg border border-line bg-card-2 px-2 py-1.5">
      <dd className="font-bold text-ink">{v}</dd>
      <dt className="text-muted">{k}</dt>
    </div>
  );
}
